spring:
  datasource:
    url: jdbc:mariadb://${MYSQL_HOST}/smart_home_hub?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&&useInnoDB=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

mqtt:
  broker: ${MQTT_BROKER_URL}
  clientId: ${MQTT_CLIENT_ID}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
smart-home-hub:
  projectId: ${PROJECT_ID}
  ssoUrl: ${SSO_URL}
  excludeUri: /auth,/login,/token,/error
logging:
  level:
    root: info
    com.ryan.project.smarthomehub: debug
  file:
    path: /tmp/log