# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push
      run: docker build -t ryantang/smart-home-hub:${GITHUB_REF##*/} . && docker push ryantang/smart-home-hub:${GITHUB_REF##*/}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  depoly-to-server:
    name: deploy to server via ssh
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: ssh to server and execute commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: cd ${{ secrets.PROJECT_HOME_DIR }} && sudo docker-compose pull && sudo docker-compose up -d