# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: copy file from remote
      run: rsync -av -e 'ssh -p 6822' ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/theta-citron-232912-firebase-adminsdk-r9n2m-42372abf77.json .
    - name: list files
      run: ls -l
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push
      run: docker build -t ryantang/smart-home-hub . && docker push ryantang/smart-home-hub
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
